apiVersion: v1
kind: Pod
metadata:
  name: coin-toss
spec:
  containers:
    - name: coin-toss
      image: busybox:1.33.1
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true;
          do
            # Record coint tosses
            if [[ $(($RANDOM % 2)) -eq 0 ]]; then echo Heads; else echo Tails; fi >> /var/log/tosses.txt;
            sleep 1;
          done
      # Mount the log directory /var/log using a volume
      volumeMounts:
        - name: varlog
          mountPath: /var/log
  # Declare log directory volume an emptyDir ephemeral volume
  volumes:
    - name: varlog
      emptyDir: {}
