apiVersion: v1
kind: Pod
metadata:
  name: load
spec:
  containers:
    - name: cpu-load
      image: cloudacademydevops/stress
      args:
        - -cpus
        - "2"
      resources:
        requests:
          cpu: "1.7"
